# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PICKYVAGABOND - Helps you with your packing list
email: pickyvagabond@gmail.com
description: >
  You think of the great escape but do not know where to start your packing list?
  Follow the guide to save time and money!

#baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/pickyvagabond"
#url: "http://127.0.0.1:4000"
#url: "https://chrisbo246.github.io/pickyvagabond" # the base hostname & protocol for your site

#twitter_username: pickyvagabond
#github_username:  chrisbo246

# Custom variables
locale: en
array: []
headers:
  api-user-agent: pickyvagabond/1.0
  origin: https://chrisbo246.github.io/pickyvagabond

# Build settings
markdown: kramdown

exclude:
  - bower_components/select2/docs/*
  - bower_components/select2-bootstrap-theme/docs/*
  - bower_components/*/tests/*

keep_files:
  - assets
  - bower_components
  - images
  - scripts


collections:
  brands:
    title: "Brands"
    output: true
    permalink: /brands/:title.html
  countries:
    title: "Countries"
    output: false
  features:
    title: "Features"
    output: false
  helps:
    title: "Helps"
    output: true
    permalink: /helps/:title.html
  matters:
    title: "Matters"
    output: false
  products:
    title: "Products"
    output: true
    permalink: /products/:title.html
  purposes:
    title: "Purposes"
    output: true
    permalink: /purposes/:title.html
  qualities:
    title: "Qualities"
    output: false
  tips:
    title: "Tips"
    output: false
  types:
    title: "Product types"
    output: true
    permalink: /types/:title.html
  users:
    title: "Users"
    output: false


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: chrisavelo
      lang: "en"
      comments: true
      image-path: "/images"
  - scope:
      path: ""
      type: brands
    values:
      layout: collection-item
      related-collections: [products, types, purposes]
      image-path: "/images/brands"
  - scope:
      path: ""
      type: countries
    values:
#      layout: country
      image-path: "/images/countries"
  - scope:
      path: ""
      type: helps
    values:
      layout: help
      image-path: "/images/helps"
  - scope:
      path: ""
      type: features
    values:
      layout: feature
      image-path: "/images/features"
  - scope:
      path: ""
      type: matters
    values:
#      layout: matter
      image-path: "/images/matters"
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: products
    values:
      layout: collection-item
      related-collections: [brands, purposes]
      image-path: "/images/products"
  - scope:
      path: ""
      type: purposes
    values:
      layout: collection-item
      related-collections: [types, products]
      image-path: "/images/purposes"
  - scope:
      path: ""
      type: qualities
    values:
#      layout: quality
      image-path: "/images/qualities"
  - scope:
      path: ""
      type: tips
    values:
      layout: tip
      image-path: "/images/tips"
  - scope:
      path: ""
      type: types
    values:
      layout: collection-item
      related-collections: [products, purposes, brands, tips]
      image-path: "/images/types"
  - scope:
      path: ""
      type: users
    values:
#      layout: user
      image-path: "/images/users"



# ------------------------------------------------------------------------------
# plugins
# ------------------------------------------------------------------------------

# https://pages.github.com/versions/
gems:
  - jekyll-github-metadata
#  - jekyll-mentions
#  - jekyll-picture-tag
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - wdm

# jekyll-github-metadata
repository: chrisbo246/pickyvagabond
github:
  url: http://127.0.0.1:4000

# jekyll-seo-tag
logo: /assets/images/logo.jpg
#social:
#  name:
#  links: []
google_site_verification: "zqEqsiPlmpNz2yZJ3A8ythPCkPXaR-v4P8sX5KW3Hd0"
twitter:
  username: chrisavelo
facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234


# jekyll-picture-tag
picture:
  source: "images/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2.0]
      attr:
        class: "default-resized-image"
        itemprop: "image"
      source_80:
        media: "(min-width: 80px)"
        width: "80"
      source_110:
        media: "(min-width: 110px)"
        width: "110"
      source_160:
        media: "(min-width: 160px)"
        width: "160"
      source_default:
        width: "250"

disqus:
  forum: pickyvagabond
  developer: 1
